openapi: 3.0.0
info:
  title: Order Management API
  version: 1.0.0
  description: API for managing orders, including creating, updating, and deleting orders.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /orders/GetAllOrdersByFilter:
    get:
      summary: Get a list of orders
      description: Retrieves a list of orders with optional filters.
      security:
        - bearerAuth: []
      parameters:
        - name: time
          in: query
          required: false
          schema:
            type: string
            description: Filter by time
            example: "2024-06-05T14:48:00.000Z"
        - name: ticketSize
          in: query
          required: false
          schema:
            type: integer
            description: Filter by ticket size
            example: "25"
        - name: issue
          in: query
          required: false
          schema:
            type: string
            description: Filter by issue
            example: "delayed, package damage"
      responses:
        '200':
          description: A list of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    orderId:
                      type: string
                      description: The unique identifier for the order.
                      example: "order123"
                    orderDate:
                      type: string
                      format: date-time
                      description: The date the order was placed.
                      example: "2024-06-05T14:48:00.000Z"
                    items:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            description: The name of the item.
                            example: "Pizza"
                          quantity:
                            type: integer
                            description: The quantity of the item.
                            example: 2
                          price:
                            type: number
                            format: float
                            description: The price of the item.
                            example: 9.99
                    customerDetails:
                      type: object
                      properties:
                        name:
                          type: string
                          description: The name of the customer.
                          example: "John Doe"
                        address:
                          type: string
                          description: The address of the customer.
                          example: "123 Main St"
                        contactInformation:
                          type: string
                          description: The contact information of the customer.
                          example: "123-456-7890"
                    paymentStatus:
                      type: string
                      description: The payment status of the order.
                      example: "paid"
                    deliveryStatus:
                      type: string
                      description: The delivery status of the order.
                      example: "delivered"
                    customerNotes:
                      type: string
                      description: Any notes from the customer.
                      example: "Please deliver to the back door."



#Get Order detail by OrderId
  /orders/GetOrderByOrderID/{orderId}:
    get:
      summary: Get order details
      description: Retrieves the details of a specific order.
      security:
        - bearerAuth: []
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            example: "order123"
      responses:
        '200':
          description: The order details
          content:
            application/json:
              schema:
                type: object
                properties:
                  orderId:
                    type: string
                    description: The unique identifier for the order.
                    example: "order123"
                  orderDate:
                    type: string
                    format: date-time
                    description: The date the order was placed.
                    example: "2024-06-05T14:48:00.000Z"
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: The name of the item.
                          example: "Pizza"
                        quantity:
                          type: integer
                          description: The quantity of the item.
                          example: 2
                        price:
                          type: number
                          format: float
                          description: The price of the item.
                          example: 9.99
                  customerDetails:
                    type: object
                    properties:
                      name:
                        type: string
                        description: The name of the customer.
                        example: "John Doe"
                      address:
                        type: string
                        description: The address of the customer.
                        example: "123 Main St"
                      contactInformation:
                        type: string
                        description: The contact information of the customer.
                        example: "123-456-7890"
                  paymentStatus:
                    type: string
                    description: The payment status of the order.
                    example: "paid"
                  deliveryStatus:
                    type: string
                    description: The delivery status of the order.
                    example: "delivered"
                  customerNotes:
                    type: string
                    description: Any notes from the customer.
                    example: "Please deliver to the back door."

    
    
   #Create new order
  /orders/CreateNewOrder:
    post:
      summary: Create a new order
      description: Creates a new order.
      security:
        - bearerAuth: []
      requestBody:
        description: The order to create.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                orderDate:
                  type: string
                  format: date-time
                  description: The date the order was placed.
                  example: "2024-06-05T14:48:00.000Z"
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: The name of the item.
                        example: "Pizza"
                      quantity:
                        type: integer
                        description: The quantity of the item.
                        example: 2
                      price:
                        type: number
                        format: float
                        description: The price of the item.
                        example: 9.99
                customerDetails:
                  type: object
                  properties:
                    name:
                      type: string
                      description: The name of the customer.
                      example: "John Doe"
                    address:
                      type: string
                      description: The address of the customer.
                      example: "123 Main St"
                    contactInformation:
                      type: string
                      description: The contact information of the customer.
                      example: "123-456-7890"
                paymentStatus:
                  type: string
                  description: The payment status of the order.
                  example: "paid"
                deliveryStatus:
                  type: string
                  description: The delivery status of the order.
                  example: "delivered"
                customerNotes:
                  type: string
                  description: Any notes from the customer.
                  example: "Please deliver to the back door."
      responses:
        '201':
          description: Order created successfully
    
  #Update Order by OrderID
  /orders/UpdateOrderByOrderID/{orderId}:
    put:
      summary: Edit order
      description: Edits an existing order.
      security:
        - bearerAuth: []
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            example: "order123"
      requestBody:
        description: The order data to update.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: The name of the item.
                        example: "Pizza"
                      quantity:
                        type: integer
                        description: The quantity of the item.
                        example: 2
                      price:
                        type: number
                        format: float
                        description: The price of the item.
                        example: 9.99
                paymentStatus:
                  type: string
                  description: The payment status of the order.
                  example: "paid"
                deliveryStatus:
                  type: string
                  description: The delivery status of the order.
                  example: "delivered"
                customerNotes:
                  type: string
                  description: Any notes from the customer.
                  example: "Please deliver to the back door."
      responses:
        '200':
          description: Order updated successfully


  
  #Delete Order by OrderID
  /orders/DeleteOrderByOrderID/{orderId}:
    delete:
      summary: Delete order
      description: Deletes an existing order.
      security:
        - bearerAuth: []
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            example: "order123"
      responses:
        '204':
          description: Order deleted successfully


