openapi: 3.0.0
info:
  title: Campaign Metrics API
  version: 1.0.0
  description: API for managing campaign metrics including creating, updating, and deleting metrics.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /campaign-metrics/GetMetricsByStoreId/{storeId}:
    get:
      summary: Get campaign metrics
      description: Retrieves metrics for tracking the performance of promotions.
      security:
        - bearerAuth: []
      parameters:
        - name: storeId
          in: path
          required: true
          schema:
            type: string
            example: "store123"
      responses:
        '200':
          description: Campaign performance metrics
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    promotionId:
                      type: string
                      description: The unique identifier for the promotion.
                      example: "promo123"
                    title:
                      type: string
                      description: The title of the promotion.
                      example: "Buy One Get One Free"
                    redemptionRate:
                      type: number
                      format: float
                      description: The redemption rate of the promotion.
                      example: 75.0
                    salesImpact:
                      type: number
                      format: float
                      description: The impact of the promotion on sales.
                      example: 15000.00
                    startDate:
                      type: string
                      format: date-time
                      description: The start date of the promotion.
                      example: "2024-07-01T00:00:00.000Z"
                    endDate:
                      type: string
                      format: date-time
                      description: The end date of the promotion.
                      example: "2024-07-31T23:59:59.000Z"

  /campaign-metrics:
    post:
      summary: Create campaign metric
      description: Creates a new campaign metric.
      security:
        - bearerAuth: []
      requestBody:
        description: The campaign metric details to create.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                storeId:
                  type: string
                  description: The unique identifier for the store.
                  example: "store123"
                promotionId:
                  type: string
                  description: The unique identifier for the promotion.
                  example: "promo123"
                title:
                  type: string
                  description: The title of the promotion.
                  example: "Buy One Get One Free"
                redemptionRate:
                  type: number
                  format: float
                  description: The redemption rate of the promotion.
                  example: 75.0
                salesImpact:
                  type: number
                  format: float
                  description: The impact of the promotion on sales.
                  example: 15000.00
                startDate:
                  type: string
                  format: date-time
                  description: The start date of the promotion.
                  example: "2024-07-01T00:00:00.000Z"
                endDate:
                  type: string
                  format: date-time
                  description: The end date of the promotion.
                  example: "2024-07-31T23:59:59.000Z"
      responses:
        '201':
          description: Campaign metric created successfully

  /campaign-metrics/{metricId}:
    put:
      summary: Update campaign metric
      description: Updates an existing campaign metric.
      security:
        - bearerAuth: []
      parameters:
        - name: metricId
          in: path
          required: true
          schema:
            type: string
            example: "metric123"
      requestBody:
        description: The campaign metric details to update.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                storeId:
                  type: string
                  description: The unique identifier for the store.
                  example: "store123"
                promotionId:
                  type: string
                  description: The unique identifier for the promotion.
                  example: "promo123"
                title:
                  type: string
                  description: The title of the promotion.
                  example: "Buy One Get One Free"
                redemptionRate:
                  type: number
                  format: float
                  description: The redemption rate of the promotion.
                  example: 75.0
                salesImpact:
                  type: number
                  format: float
                  description: The impact of the promotion on sales.
                  example: 15000.00
                startDate:
                  type: string
                  format: date-time
                  description: The start date of the promotion.
                  example: "2024-07-01T00:00:00.000Z"
                endDate:
                  type: string
                  format: date-time
                  description: The end date of the promotion.
                  example: "2024-07-31T23:59:59.000Z"
      responses:
        '200':
          description: Campaign metric updated successfully

    delete:
      summary: Delete campaign metric
      description: Deletes a specific campaign metric.
      security:
        - bearerAuth: []
      parameters:
        - name: metricId
          in: path
          required: true
          schema:
            type: string
            example: "metric123"
      responses:
        '204':
          description: Campaign metric deleted successfully